"""initial schema

Revision ID: 2c0bbf5c7554
Revises:
Create Date: 2026-10-02 06:46:08.612739

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c0bbf5c7554"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "integrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("secret_ref", sa.Text(), nullable=True),
        sa.Column("detected_version", sa.String(length=80), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("health_state", sa.String(length=20), nullable=False),
        sa.Column("last_health_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind"),
    )
    op.create_table(
        "libraries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("jellyfin_library_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jellyfin_library_id"),
    )
    op.create_table(
        "library_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("library_id", sa.String(length=36), nullable=False),
        sa.Column("policy_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id"),
    )
    op.create_table(
        "media_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("library_id", sa.String(length=36), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("sort_title", sa.String(length=512), nullable=True),
        sa.Column("jellyfin_id", sa.String(length=100), nullable=True),
        sa.Column("sonarr_id", sa.Integer(), nullable=True),
        sa.Column("radarr_id", sa.Integer(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(length=100), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("missing_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("media_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_identities_imdb_id"), ["imdb_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_media_identities_jellyfin_id"), ["jellyfin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_media_identities_radarr_id"), ["radarr_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_media_identities_sonarr_id"), ["sonarr_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_media_identities_tmdb_id"), ["tmdb_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_media_identities_tvdb_id"), ["tvdb_id"], unique=False
        )

    op.create_table(
        "acquisition_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("highest_demonstrated_season", sa.Integer(), nullable=True),
        sa.Column("target_next_season", sa.Integer(), nullable=True),
        sa.Column("plan_revision", sa.Integer(), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_identity_id"),
    )
    op.create_table(
        "lifecycle_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_event_id", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=True),
        sa.Column("jellyfin_user_id", sa.String(length=100), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("normalized_json", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_event_id"),
    )
    op.create_table(
        "media_parts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=True),
        sa.Column("jellyfin_id", sa.String(length=100), nullable=True),
        sa.Column("sonarr_episode_id", sa.Integer(), nullable=True),
        sa.Column("arr_file_id", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("has_file", sa.Boolean(), nullable=False),
        sa.Column("air_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "media_identity_id", "kind", "season_number", "episode_number"
        ),
    )
    with op.batch_alter_table("media_parts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_media_parts_jellyfin_id"), ["jellyfin_id"], unique=False
        )

    op.create_table(
        "purge_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("candidate_revision", sa.Integer(), nullable=False),
        sa.Column("reason_code", sa.String(length=50), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("reclaimable_bytes", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("score_detail_json", sa.JSON(), nullable=True),
        sa.Column("eligible_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_snapshot", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_delete_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snooze_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purge_candidates", schema=None) as batch_op:
        batch_op.create_index(
            "uq_active_candidate",
            ["media_identity_id"],
            unique=True,
            sqlite_where=sa.text(
                "state IN ('ELIGIBLE', 'REVIEW', 'LEAVING_SOON', 'SNOOZED', 'APPROVED', 'EXECUTING')"
            ),
            postgresql_where=sa.text(
                "state IN ('ELIGIBLE', 'REVIEW', 'LEAVING_SOON', 'SNOOZED', 'APPROVED', 'EXECUTING')"
            ),
        )

    op.create_table(
        "title_overrides",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=False),
        sa.Column("override_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_identity_id"),
    )
    op.create_table(
        "user_media_state",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=False),
        sa.Column("jellyfin_user_id", sa.String(length=100), nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_episode_count", sa.Integer(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_identity_id", "jellyfin_user_id"),
    )
    op.create_table(
        "watch_state_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=False),
        sa.Column("jellyfin_user_id", sa.String(length=100), nullable=False),
        sa.Column("provider_key", sa.String(length=100), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=True),
        sa.Column("played", sa.Boolean(), nullable=False),
        sa.Column("playback_position_ticks", sa.BigInteger(), nullable=False),
        sa.Column("date_played", sa.DateTime(timezone=True), nullable=True),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "episode_user_state",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_part_id", sa.String(length=36), nullable=False),
        sa.Column("jellyfin_user_id", sa.String(length=100), nullable=False),
        sa.Column("played", sa.Boolean(), nullable=False),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("playback_position_ticks", sa.BigInteger(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_part_id"],
            ["media_parts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_part_id", "jellyfin_user_id"),
    )
    op.create_table(
        "lifecycle_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=True),
        sa.Column("candidate_id", sa.String(length=36), nullable=True),
        sa.Column("event_id", sa.String(length=36), nullable=True),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["purge_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["lifecycle_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "poster_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("media_identity_id", sa.String(length=36), nullable=False),
        sa.Column("jellyfin_item_id", sa.String(length=100), nullable=False),
        sa.Column("original_image_tag", sa.String(length=100), nullable=True),
        sa.Column("original_image_bytes_path", sa.String(length=512), nullable=True),
        sa.Column("candidate_id", sa.String(length=36), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["purge_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_identity_id"],
            ["media_identities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("poster_snapshots")
    op.drop_table("lifecycle_actions")
    op.drop_table("episode_user_state")
    op.drop_table("watch_state_snapshots")
    op.drop_table("user_media_state")
    op.drop_table("title_overrides")
    with op.batch_alter_table("purge_candidates", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_candidate",
            sqlite_where=sa.text(
                "state IN ('ELIGIBLE', 'REVIEW', 'LEAVING_SOON', 'SNOOZED', 'APPROVED', 'EXECUTING')"
            ),
            postgresql_where=sa.text(
                "state IN ('ELIGIBLE', 'REVIEW', 'LEAVING_SOON', 'SNOOZED', 'APPROVED', 'EXECUTING')"
            ),
        )

    op.drop_table("purge_candidates")
    with op.batch_alter_table("media_parts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_parts_jellyfin_id"))

    op.drop_table("media_parts")
    op.drop_table("lifecycle_events")
    op.drop_table("acquisition_states")
    with op.batch_alter_table("media_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_media_identities_tvdb_id"))
        batch_op.drop_index(batch_op.f("ix_media_identities_tmdb_id"))
        batch_op.drop_index(batch_op.f("ix_media_identities_sonarr_id"))
        batch_op.drop_index(batch_op.f("ix_media_identities_radarr_id"))
        batch_op.drop_index(batch_op.f("ix_media_identities_jellyfin_id"))
        batch_op.drop_index(batch_op.f("ix_media_identities_imdb_id"))

    op.drop_table("media_identities")
    op.drop_table("library_policies")
    op.drop_table("libraries")
    op.drop_table("integrations")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
