"""track generated poster path

Revision ID: b29dd0e38f2b
Revises: 2c0bbf5c7554
Create Date: 2026-10-02 06:53:25.657377

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b29dd0e38f2b"
down_revision = "2c0bbf5c7554"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("poster_snapshots", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("badged_image_bytes_path", sa.String(length=512), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("poster_snapshots", schema=None) as batch_op:
        batch_op.drop_column("badged_image_bytes_path")

    # ### end Alembic commands ###
