"""add database job leases

Revision ID: bdf37dc1d2e6
Revises: 38f971d7ab87
Create Date: 2026-10-02 08:01:26.128291

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bdf37dc1d2e6"
down_revision = "38f971d7ab87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_leases",
        sa.Column("scope", sa.String(length=150), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("scope"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_leases")
    # ### end Alembic commands ###
