"""track media acquisition time

Revision ID: 38f971d7ab87
Revises: b29dd0e38f2b
Create Date: 2026-10-02 07:08:53.126691

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38f971d7ab87"
down_revision = "b29dd0e38f2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_parts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media_parts", schema=None) as batch_op:
        batch_op.drop_column("acquired_at")

    # ### end Alembic commands ###
